### ISSUE TITLE
error in best

### ISSUE THREAD

**Issue by ralanburnett** [jrzaurin/LightGBM-with-Focal-Loss#1]
I am using my own dataset with X and Y read in as Pandas dataframes (followed by train-valid-split)

I'm getting the following error in best.
best = fmin(fn=objective,
            space=space,
            algo=tpe.suggest,
            max_evals=5,
            trials=trials)
ValueError                                Traceback (most recent call last)
<ipython-input-31-6f56c63a5097> in <module>
      7             algo=tpe.suggest,
      8             max_evals=5,
----> 9             trials=trials)

--> 729                                                                                              self.pandas_categorical)
    730         label = _label_from_pandas(label)
    731         self.data_has_header = False

~\Anaconda3\envs\tensorflow-gpu+SHAP\lib\site-packages\lightgbm\basic.py in _data_from_pandas(data, feature_name, categorical_feature, pandas_categorical)
    245         if len(data.shape) != 2 or data.shape[0] < 1:
    246             raise ValueError('Input data must be 2 dimensional and non empty.')
--> 247         if feature_name == 'auto' or feature_name is None:
    248             data = data.rename(columns=str)
    249         cat_cols = data.select_dtypes(include=['category']).columns

all of my features have names; the feature_names are
Index(['acft_make_CESSNA', 'acft_make_PIPER', 'acft_make_BEECH',
       'acft_make_LUSCOMBE', 'acft_make_PITTS', 'acft_make_CHAMPION',
       'acft_make_MOONEY', 'acft_make_NORTH AMERICAN', 'acft_make_BELLANCA',
       'acft_make_AERONCA',
       ...
       'pc_profession_ENGR', 'pc_profession_DOCD', 'pc_profession_PMIL',
       'pc_profession_OCP ', 'pc_profession_FARA', 'pc_profession_UNK',
       'pc_profession_N   ', 'pc_profession_Y   ', 'pc_profession_NOCP',
       'pc_profession_CLGY'],
      dtype='object', length=790)

Any ideas to what might be wrong?

**Comment by jrzaurin** [comment]
Hi @ralanburnett 

Thanks for emailing me and closing the issue. Glad you sorted out :)
